# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_1/AlohaHE_xbar_1.xci
# IP: The module: 'AlohaHE_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_1/AlohaHE_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AlohaHE_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_1/AlohaHE_xbar_1.xci
# IP: The module: 'AlohaHE_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_1/AlohaHE_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AlohaHE_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
