# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.cache/wt [current_project]
set_property parent.project_path /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/fkrieger/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:genesys2:part0:1.1 [current_project]
set_property ip_output_repo /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Common/MemoryInitializationFiles/FFTStoredTwiddleFactors.coe
add_files /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Common/MemoryInitializationFiles/TwFctrCache_RNSConsts.coe
read_verilog -library xil_defaultlib /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/hdl/AlohaHE_wrapper.v
add_files /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/AlohaHE.bd
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_bram_ctrl_0_0/AlohaHE_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_cdma_0_0/AlohaHE_axi_cdma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_cdma_0_0/AlohaHE_axi_cdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_0/AlohaHE_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_1/bd_7499_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_1/bd_7499_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_2/bd_7499_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_2/bd_7499_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_3/bd_7499_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_3/bd_7499_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_4/bd_7499_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_5/bd_7499_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_6/bd_7499_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_7/bd_7499_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_8/bd_7499_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_12/bd_7499_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_13/bd_7499_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_14/bd_7499_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_15/bd_7499_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_16/bd_7499_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_17/bd_7499_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_21/bd_7499_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_22/bd_7499_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_23/bd_7499_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_27/bd_7499_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_28/bd_7499_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_29/bd_7499_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_30/bd_7499_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_31/bd_7499_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_32/bd_7499_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_33/bd_7499_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_34/bd_7499_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_35/bd_7499_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_36/bd_7499_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_37/bd_7499_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_smc_0/bd_0/ip/ip_38/bd_7499_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_timer_0_0/AlohaHE_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_timer_0_0/AlohaHE_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_uartlite_0_0/AlohaHE_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_uartlite_0_0/AlohaHE_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_axi_uartlite_0_0/AlohaHE_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_clk_wiz_0_0/AlohaHE_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_clk_wiz_0_0/AlohaHE_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_clk_wiz_0_0/AlohaHE_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_mdm_1_0/AlohaHE_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_mdm_1_0/AlohaHE_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_xbar_1/AlohaHE_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_microblaze_1_0/AlohaHE_microblaze_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_microblaze_1_0/AlohaHE_microblaze_1_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_microblaze_1_0/AlohaHE_microblaze_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_dlmb_bram_if_cntlr_0/AlohaHE_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_dlmb_v10_0/AlohaHE_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_dlmb_v10_0/AlohaHE_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ilmb_bram_if_cntlr_0/AlohaHE_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ilmb_v10_0/AlohaHE_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ilmb_v10_0/AlohaHE_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_lmb_bram_0/AlohaHE_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_mig_7series_0_0/AlohaHE_mig_7series_0_0/user_design/constraints/AlohaHE_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_mig_7series_0_0/AlohaHE_mig_7series_0_0/user_design/constraints/AlohaHE_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_mig_7series_0_0/AlohaHE_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_proc_sys_reset_0_0/AlohaHE_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_proc_sys_reset_0_0/AlohaHE_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_proc_sys_reset_0_0/AlohaHE_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_rst_mig_7series_0_100M_0/AlohaHE_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_rst_mig_7series_0_100M_0/AlohaHE_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_rst_mig_7series_0_100M_0/AlohaHE_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/AlohaHE_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_Kintex/Aloha-HE_Kintex.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_microblaze_1_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top AlohaHE_wrapper -part xc7k325tffg900-2 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef AlohaHE_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file AlohaHE_wrapper_utilization_synth.rpt -pb AlohaHE_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
