# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0.xci
# IP: The module: 'AlohaHE_ComputeCoreWrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/INS_RAM/INS_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTAllTwiddleROM/FFTAllTwiddleROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTAllTwiddleROM || ORIG_REF_NAME==FFTAllTwiddleROM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/MontRed_DSP_Mult/MontRed_DSP_Mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_Mult || ORIG_REF_NAME==MontRed_DSP_Mult} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/MontRed_DSP_MultAdd/MontRed_DSP_MultAdd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_MultAdd || ORIG_REF_NAME==MontRed_DSP_MultAdd} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B_doublebuffer/DSP_A_x_B_doublebuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_doublebuffer || ORIG_REF_NAME==DSP_A_x_B_doublebuffer} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B_p_C/DSP_A_x_B_p_C.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_p_C || ORIG_REF_NAME==DSP_A_x_B_p_C} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B/DSP_A_x_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B || ORIG_REF_NAME==DSP_A_x_B} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTTw_RNS_ROM || ORIG_REF_NAME==FFTTw_RNS_ROM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/TernaryPolyBRAM/TernaryPolyBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TernaryPolyBRAM || ORIG_REF_NAME==TernaryPolyBRAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/CBDPolyBRAM/CBDPolyBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CBDPolyBRAM || ORIG_REF_NAME==CBDPolyBRAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/NTTPolyBank/NTTPolyBank.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NTTPolyBank || ORIG_REF_NAME==NTTPolyBank} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/SharedFFTBramBank/SharedFFTBramBank.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SharedFFTBramBank || ORIG_REF_NAME==SharedFFTBramBank} -quiet] -quiet

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTAllTwiddleROM/FFTAllTwiddleROM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/TernaryPolyBRAM/TernaryPolyBRAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/CBDPolyBRAM/CBDPolyBRAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/NTTPolyBank/NTTPolyBank_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/SharedFFTBramBank/SharedFFTBramBank_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AlohaHE_ComputeCoreWrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0.xci
# IP: The module: 'AlohaHE_ComputeCoreWrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/INS_RAM/INS_RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTAllTwiddleROM/FFTAllTwiddleROM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTAllTwiddleROM || ORIG_REF_NAME==FFTAllTwiddleROM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/MontRed_DSP_Mult/MontRed_DSP_Mult.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_Mult || ORIG_REF_NAME==MontRed_DSP_Mult} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/MontRed_DSP_MultAdd/MontRed_DSP_MultAdd.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_MultAdd || ORIG_REF_NAME==MontRed_DSP_MultAdd} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B_doublebuffer/DSP_A_x_B_doublebuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_doublebuffer || ORIG_REF_NAME==DSP_A_x_B_doublebuffer} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B_p_C/DSP_A_x_B_p_C.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_p_C || ORIG_REF_NAME==DSP_A_x_B_p_C} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/DSP_A_x_B/DSP_A_x_B.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B || ORIG_REF_NAME==DSP_A_x_B} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTTw_RNS_ROM || ORIG_REF_NAME==FFTTw_RNS_ROM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/TernaryPolyBRAM/TernaryPolyBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TernaryPolyBRAM || ORIG_REF_NAME==TernaryPolyBRAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/CBDPolyBRAM/CBDPolyBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CBDPolyBRAM || ORIG_REF_NAME==CBDPolyBRAM} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/NTTPolyBank/NTTPolyBank.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NTTPolyBank || ORIG_REF_NAME==NTTPolyBank} -quiet] -quiet

# IP: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/SharedFFTBramBank/SharedFFTBramBank.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SharedFFTBramBank || ORIG_REF_NAME==SharedFFTBramBank} -quiet] -quiet

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTAllTwiddleROM/FFTAllTwiddleROM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/TernaryPolyBRAM/TernaryPolyBRAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/CBDPolyBRAM/CBDPolyBRAM_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/NTTPolyBank/NTTPolyBank_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/ip/SharedFFTBramBank/SharedFFTBramBank_ooc.xdc

# XDC: /home/fkrieger/Desktop/Aloha-HE/Aloha-HE_ZYNQ/Aloha-HE_ZYNQ.srcs/sources_1/bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AlohaHE_ComputeCoreWrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
