# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/INS_RAM/INS_RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/FFTAllTwiddleROM/FFTAllTwiddleROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTAllTwiddleROM || ORIG_REF_NAME==FFTAllTwiddleROM} -quiet] -quiet

# IP: ip/MontRed_DSP_Mult/MontRed_DSP_Mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_Mult || ORIG_REF_NAME==MontRed_DSP_Mult} -quiet] -quiet

# IP: ip/MontRed_DSP_MultAdd/MontRed_DSP_MultAdd.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_MultAdd || ORIG_REF_NAME==MontRed_DSP_MultAdd} -quiet] -quiet

# IP: ip/DSP_A_x_B_doublebuffer/DSP_A_x_B_doublebuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_doublebuffer || ORIG_REF_NAME==DSP_A_x_B_doublebuffer} -quiet] -quiet

# IP: ip/DSP_A_x_B_p_C/DSP_A_x_B_p_C.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_p_C || ORIG_REF_NAME==DSP_A_x_B_p_C} -quiet] -quiet

# IP: ip/DSP_A_x_B/DSP_A_x_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B || ORIG_REF_NAME==DSP_A_x_B} -quiet] -quiet

# IP: ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTTw_RNS_ROM || ORIG_REF_NAME==FFTTw_RNS_ROM} -quiet] -quiet

# IP: ip/TernaryPolyBRAM/TernaryPolyBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TernaryPolyBRAM || ORIG_REF_NAME==TernaryPolyBRAM} -quiet] -quiet

# IP: ip/CBDPolyBRAM/CBDPolyBRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CBDPolyBRAM || ORIG_REF_NAME==CBDPolyBRAM} -quiet] -quiet

# IP: ip/NTTPolyBank/NTTPolyBank.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NTTPolyBank || ORIG_REF_NAME==NTTPolyBank} -quiet] -quiet

# IP: ip/SharedFFTBramBank/SharedFFTBramBank.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SharedFFTBramBank || ORIG_REF_NAME==SharedFFTBramBank} -quiet] -quiet

# Block Designs: bd/AlohaHE/AlohaHE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE || ORIG_REF_NAME==AlohaHE} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_ComputeCoreWrapper_0_0/AlohaHE_ComputeCoreWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_ComputeCoreWrapper_0_0 || ORIG_REF_NAME==AlohaHE_ComputeCoreWrapper_0_0} -quiet] -quiet

# IP: ip/INS_RAM/INS_RAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INS_RAM || ORIG_REF_NAME==INS_RAM} -quiet] -quiet

# IP: ip/FFTAllTwiddleROM/FFTAllTwiddleROM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTAllTwiddleROM || ORIG_REF_NAME==FFTAllTwiddleROM} -quiet] -quiet

# IP: ip/MontRed_DSP_Mult/MontRed_DSP_Mult.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_Mult || ORIG_REF_NAME==MontRed_DSP_Mult} -quiet] -quiet

# IP: ip/MontRed_DSP_MultAdd/MontRed_DSP_MultAdd.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MontRed_DSP_MultAdd || ORIG_REF_NAME==MontRed_DSP_MultAdd} -quiet] -quiet

# IP: ip/DSP_A_x_B_doublebuffer/DSP_A_x_B_doublebuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_doublebuffer || ORIG_REF_NAME==DSP_A_x_B_doublebuffer} -quiet] -quiet

# IP: ip/DSP_A_x_B_p_C/DSP_A_x_B_p_C.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B_p_C || ORIG_REF_NAME==DSP_A_x_B_p_C} -quiet] -quiet

# IP: ip/DSP_A_x_B/DSP_A_x_B.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DSP_A_x_B || ORIG_REF_NAME==DSP_A_x_B} -quiet] -quiet

# IP: ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFTTw_RNS_ROM || ORIG_REF_NAME==FFTTw_RNS_ROM} -quiet] -quiet

# IP: ip/TernaryPolyBRAM/TernaryPolyBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TernaryPolyBRAM || ORIG_REF_NAME==TernaryPolyBRAM} -quiet] -quiet

# IP: ip/CBDPolyBRAM/CBDPolyBRAM.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CBDPolyBRAM || ORIG_REF_NAME==CBDPolyBRAM} -quiet] -quiet

# IP: ip/NTTPolyBank/NTTPolyBank.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NTTPolyBank || ORIG_REF_NAME==NTTPolyBank} -quiet] -quiet

# IP: ip/SharedFFTBramBank/SharedFFTBramBank.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SharedFFTBramBank || ORIG_REF_NAME==SharedFFTBramBank} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_axi_bram_ctrl_0_0/AlohaHE_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_axi_bram_ctrl_0_0 || ORIG_REF_NAME==AlohaHE_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_axi_cdma_0_0/AlohaHE_axi_cdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_axi_cdma_0_0 || ORIG_REF_NAME==AlohaHE_axi_cdma_0_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_xbar_0/AlohaHE_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_xbar_0 || ORIG_REF_NAME==AlohaHE_xbar_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_axi_interconnect_0_0/AlohaHE_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_axi_interconnect_0_0 || ORIG_REF_NAME==AlohaHE_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_processing_system7_0_0/AlohaHE_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_processing_system7_0_0 || ORIG_REF_NAME==AlohaHE_processing_system7_0_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_ps7_0_axi_periph_0/AlohaHE_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_ps7_0_axi_periph_0 || ORIG_REF_NAME==AlohaHE_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_ps7_0_axi_periph_1_0/AlohaHE_ps7_0_axi_periph_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_ps7_0_axi_periph_1_0 || ORIG_REF_NAME==AlohaHE_ps7_0_axi_periph_1_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_rst_ps7_0_100M_0/AlohaHE_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_rst_ps7_0_100M_0 || ORIG_REF_NAME==AlohaHE_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_AXISlave8Ports_0_0/AlohaHE_AXISlave8Ports_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_AXISlave8Ports_0_0 || ORIG_REF_NAME==AlohaHE_AXISlave8Ports_0_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_auto_pc_0/AlohaHE_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_auto_pc_0 || ORIG_REF_NAME==AlohaHE_auto_pc_0} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_auto_pc_1/AlohaHE_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_auto_pc_1 || ORIG_REF_NAME==AlohaHE_auto_pc_1} -quiet] -quiet

# IP: bd/AlohaHE/ip/AlohaHE_auto_pc_2/AlohaHE_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AlohaHE_auto_pc_2 || ORIG_REF_NAME==AlohaHE_auto_pc_2} -quiet] -quiet

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/FFTAllTwiddleROM/FFTAllTwiddleROM_ooc.xdc

# XDC: ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM_ooc.xdc

# XDC: ip/TernaryPolyBRAM/TernaryPolyBRAM_ooc.xdc

# XDC: ip/CBDPolyBRAM/CBDPolyBRAM_ooc.xdc

# XDC: ip/NTTPolyBank/NTTPolyBank_ooc.xdc

# XDC: ip/SharedFFTBramBank/SharedFFTBramBank_ooc.xdc

# XDC: ip/INS_RAM/INS_RAM_ooc.xdc

# XDC: ip/FFTAllTwiddleROM/FFTAllTwiddleROM_ooc.xdc

# XDC: ip/FFTTw_RNS_ROM/FFTTw_RNS_ROM_ooc.xdc

# XDC: ip/TernaryPolyBRAM/TernaryPolyBRAM_ooc.xdc

# XDC: ip/CBDPolyBRAM/CBDPolyBRAM_ooc.xdc

# XDC: ip/NTTPolyBank/NTTPolyBank_ooc.xdc

# XDC: ip/SharedFFTBramBank/SharedFFTBramBank_ooc.xdc

# XDC: bd/AlohaHE/AlohaHE_ooc.xdc
